export const CREATE_NEW_HEADER = 'CREATE_NEW_HEADER';
export const REMOVE_HEADER = 'REMOVE_HEADER';
export const CREATE_NEW_EDUCATION = 'CREATE_NEW_EDUCATION';
export const REMOVE_EDUCATION = 'REMOVE_EDUCATION';
export const CREATE_NEW_EXPERIENCE = 'CREATE_NEW_EXPERIENCE';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
export const CREATE_NEW_SKILLS = 'CREATE_NEW_SKILLS';
export const REMOVE_SKILLS = 'REMOVE_SKILLS';